services:
  web:
    build: ./app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate; python manage.py create_superuser; python manage.py load_sample_data; gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file:
      - .env
volumes:
  static_volume:
  media_volume:
